name: Test Docker Build and Push
on:
  push:
    branches: [ main ]
permissions:
  contents: read
jobs:
  test-build:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
    - name: Generate vendor directory
      run: go mod vendor
      
    - name: Clone ScanCode Toolkit
      run: git clone https://github.com/aboutcode-org/scancode-toolkit 
      
    - name: Build ScanCode Docker image
      run: |
        cd scancode-toolkit
        docker build --tag scancode-toolkit .    
      
    - name: Run ScanCode to generate license information
      run: docker run -v ${PWD}:/mps-router scancode-toolkit -c -l --license-text --json-pp /mps-router/licenses.json /mps-router/vendor
      
    - name: Copy License Scan Result
      run: |
        mkdir -p licenses
        cp licenses.json ./licenses/licenses.json
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.10.0
      
    - name: Docker Login to DockerHub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@0a51e81a6baff2acad3ee88f4121c589c73d0f0e # v4.2.0
      with:
        semantic_version: 19.0.5
        extra_plugins: |
          @semantic-release/exec@6.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}